language: ruby

before_install:
  - export ANDROID_OS=$ANDROID_TARGET
#  - sudo apt-get update -qq
#  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - wget http://ci.jruby.org/snapshots/master/jruby-jars-${MASTER}.gem
  - if [ "$JRUBY_JARS_VERSION" == "" ] ; then export JRUBY_JARS_VERSION=$MASTER ; fi

rvm:
  - ruby

jdk:
  - oraclejdk8

env:
  global:
    - RUBOTO_UPDATE_EXAMPLES=0
    - MASTER=9000.dev
  matrix:
    - ANDROID_TARGET=17 RUBOTO_PLATFORM=CURRENT    TEST_PART=1of3
    - ANDROID_TARGET=17 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=1of3
    - ANDROID_TARGET=17 RUBOTO_PLATFORM=STANDALONE TEST_PART=1of3
    - ANDROID_TARGET=17 RUBOTO_PLATFORM=STANDALONE TEST_PART=2of3 JRUBY_JARS_VERSION=1.7.11
    - ANDROID_TARGET=17 RUBOTO_PLATFORM=STANDALONE TEST_PART=3of3 JRUBY_JARS_VERSION=1.7.10

    - ANDROID_TARGET=16 RUBOTO_PLATFORM=CURRENT    TEST_PART=2of3
    - ANDROID_TARGET=16 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=2of3
    - ANDROID_TARGET=16 RUBOTO_PLATFORM=STANDALONE TEST_PART=1of3 JRUBY_JARS_VERSION=1.7.10
    - ANDROID_TARGET=16 RUBOTO_PLATFORM=STANDALONE TEST_PART=2of3
    - ANDROID_TARGET=16 RUBOTO_PLATFORM=STANDALONE TEST_PART=3of3 JRUBY_JARS_VERSION=1.7.11

    - ANDROID_TARGET=15 RUBOTO_PLATFORM=CURRENT    TEST_PART=3of3
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=3of3
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=1of3 JRUBY_JARS_VERSION=1.7.11
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=2of3 JRUBY_JARS_VERSION=1.7.10
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=3of3

matrix:
  fast_finish: true
  allow_failures:
    - env: "ANDROID_TARGET=17 RUBOTO_PLATFORM=FROM_GEM"
    - env: "ANDROID_TARGET=17 RUBOTO_PLATFORM=STANDALONE TEST_PART=2of3"
    - env: "ANDROID_TARGET=16 RUBOTO_PLATFORM=FROM_GEM"

script:
    - rake install
    - ruboto setup -y -t 10 -t $ANDROID_TARGET
    - source ~/.rubotorc
    - ruboto emulator -t $ANDROID_TARGET
    - ./run_tests.sh

notifications:
  irc: "irc.freenode.org#ruboto"
