language: android

before_install:
  - export ANDROID_OS=$ANDROID_TARGET
  - wget http://ci.jruby.org/snapshots/master/jruby-jars-${MASTER}.gem
  - if [ "$JRUBY_JARS_VERSION" == "" ] ; then export JRUBY_JARS_VERSION=$MASTER ; fi

env:
  global:
    - RUBOTO_UPDATE_EXAMPLES=0
    - MASTER=9000.dev
  matrix:
    - ANDROID_TARGET=17 RUBOTO_PLATFORM=CURRENT    TEST_PART=1of5
    - ANDROID_TARGET=17 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=2of5
    - ANDROID_TARGET=17 RUBOTO_PLATFORM=STANDALONE TEST_PART=3of5
    - ANDROID_TARGET=17 RUBOTO_PLATFORM=STANDALONE TEST_PART=4of5 JRUBY_JARS_VERSION=1.7.11
    - ANDROID_TARGET=17 RUBOTO_PLATFORM=STANDALONE TEST_PART=5of5 JRUBY_JARS_VERSION=1.7.12

    - ANDROID_TARGET=16 RUBOTO_PLATFORM=CURRENT    TEST_PART=1of5
    - ANDROID_TARGET=16 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=2of5
    - ANDROID_TARGET=16 RUBOTO_PLATFORM=STANDALONE TEST_PART=3of5 JRUBY_JARS_VERSION=1.7.12
    - ANDROID_TARGET=16 RUBOTO_PLATFORM=STANDALONE TEST_PART=4of5
    - ANDROID_TARGET=16 RUBOTO_PLATFORM=STANDALONE TEST_PART=5of5 JRUBY_JARS_VERSION=1.7.11

    - ANDROID_TARGET=15 RUBOTO_PLATFORM=CURRENT    TEST_PART=1of5
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=2of5
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=3of5 JRUBY_JARS_VERSION=1.7.11
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=4of5 JRUBY_JARS_VERSION=1.7.12
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=5of5

    - ANDROID_TARGET=10 RUBOTO_PLATFORM=CURRENT

matrix:
  fast_finish: true
  allow_failures:
    - env: ANDROID_TARGET=17 RUBOTO_PLATFORM=STANDALONE TEST_PART=3of5
    - env: ANDROID_TARGET=17 RUBOTO_PLATFORM=STANDALONE TEST_PART=5of5
    - env: ANDROID_TARGET=10 RUBOTO_PLATFORM=CURRENT

script:
    - rake install
    - ruboto setup -y -t 10 -t $ANDROID_TARGET
    - source ~/.rubotorc
    - ruboto emulator -t $ANDROID_TARGET
    - ./run_tests.sh

notifications:
  irc: "irc.freenode.org#ruboto"
