# http://docs.travis-ci.com/user/languages/android/
language: android
android:
  components:
    - build-tools-20.0.0

before_install:
  - export ANDROID_OS=$ANDROID_TARGET
  - if [ "$JRUBY_JARS_VERSION" == "MASTER" ] || [ "$JRUBY_JARS_VERSION" == "STABLE" ] ; then rake get_jruby_jars_snapshots ; fi
  - STABLE=`ls jruby-jars-*.gem | head -n 1 | cut -f 3 -d'-' | sed s/\\.gem//`
  - MASTER=`ls jruby-jars-*.gem | tail -n 1 | cut -f 3 -d'-' | sed s/\\.gem//`
  - if [ "$JRUBY_JARS_VERSION" == "MASTER" ] ; then export JRUBY_JARS_VERSION=$MASTER ; fi
  - if [ "$JRUBY_JARS_VERSION" == "STABLE" ] ; then export JRUBY_JARS_VERSION=$STABLE ; fi

env:
  global:
    - RUBOTO_UPDATE_EXAMPLES=0

  matrix:
    - ANDROID_TARGET=L RUBOTO_PLATFORM=CURRENT    TEST_PART=1of5
    - ANDROID_TARGET=L RUBOTO_PLATFORM=FROM_GEM   TEST_PART=2of5 JRUBY_JARS_VERSION=MASTER
    - ANDROID_TARGET=L RUBOTO_PLATFORM=FROM_GEM   TEST_PART=3of5 JRUBY_JARS_VERSION=STABLE
    - ANDROID_TARGET=L RUBOTO_PLATFORM=STANDALONE TEST_PART=4of5 JRUBY_JARS_VERSION=MASTER
    - ANDROID_TARGET=L RUBOTO_PLATFORM=STANDALONE TEST_PART=5of5 JRUBY_JARS_VERSION=STABLE
    - ANDROID_TARGET=L RUBOTO_PLATFORM=STANDALONE TEST_PART=1of5 JRUBY_JARS_VERSION=1.7.15
    - ANDROID_TARGET=L RUBOTO_PLATFORM=STANDALONE TEST_PART=2of5 JRUBY_JARS_VERSION=1.7.13

    - ANDROID_TARGET=19 RUBOTO_PLATFORM=CURRENT    TEST_PART=2of5
    - ANDROID_TARGET=19 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=3of5 JRUBY_JARS_VERSION=MASTER
    - ANDROID_TARGET=19 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=4of5 JRUBY_JARS_VERSION=STABLE
    - ANDROID_TARGET=19 RUBOTO_PLATFORM=STANDALONE TEST_PART=5of5 JRUBY_JARS_VERSION=MASTER
    - ANDROID_TARGET=19 RUBOTO_PLATFORM=STANDALONE TEST_PART=1of5 JRUBY_JARS_VERSION=STABLE
    - ANDROID_TARGET=19 RUBOTO_PLATFORM=STANDALONE TEST_PART=2of5 JRUBY_JARS_VERSION=1.7.15
    - ANDROID_TARGET=19 RUBOTO_PLATFORM=STANDALONE TEST_PART=3of5 JRUBY_JARS_VERSION=1.7.13

    - ANDROID_TARGET=17 RUBOTO_PLATFORM=CURRENT    TEST_PART=3of5
    - ANDROID_TARGET=17 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=4of5 JRUBY_JARS_VERSION=MASTER
    - ANDROID_TARGET=17 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=5of5 JRUBY_JARS_VERSION=STABLE
    - ANDROID_TARGET=17 RUBOTO_PLATFORM=STANDALONE TEST_PART=1of5 JRUBY_JARS_VERSION=MASTER
    - ANDROID_TARGET=17 RUBOTO_PLATFORM=STANDALONE TEST_PART=2of5 JRUBY_JARS_VERSION=STABLE
    - ANDROID_TARGET=17 RUBOTO_PLATFORM=STANDALONE TEST_PART=3of5 JRUBY_JARS_VERSION=1.7.15
    - ANDROID_TARGET=17 RUBOTO_PLATFORM=STANDALONE TEST_PART=4of5 JRUBY_JARS_VERSION=1.7.13

    - ANDROID_TARGET=16 RUBOTO_PLATFORM=CURRENT    TEST_PART=4of5
    - ANDROID_TARGET=16 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=5of5 JRUBY_JARS_VERSION=MASTER
    - ANDROID_TARGET=16 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=1of5 JRUBY_JARS_VERSION=STABLE
    - ANDROID_TARGET=16 RUBOTO_PLATFORM=STANDALONE TEST_PART=2of5 JRUBY_JARS_VERSION=MASTER
    - ANDROID_TARGET=16 RUBOTO_PLATFORM=STANDALONE TEST_PART=3of5 JRUBY_JARS_VERSION=STABLE
    - ANDROID_TARGET=16 RUBOTO_PLATFORM=STANDALONE TEST_PART=4of5 JRUBY_JARS_VERSION=1.7.15
    - ANDROID_TARGET=16 RUBOTO_PLATFORM=STANDALONE TEST_PART=5of5 JRUBY_JARS_VERSION=1.7.13

    - ANDROID_TARGET=15 RUBOTO_PLATFORM=CURRENT    TEST_PART=5of5
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=1of5 JRUBY_JARS_VERSION=MASTER
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=2of5 JRUBY_JARS_VERSION=STABLE
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=3of5 JRUBY_JARS_VERSION=MASTER
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=4of5 JRUBY_JARS_VERSION=STABLE
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=5of5 JRUBY_JARS_VERSION=1.7.15
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=1of5 JRUBY_JARS_VERSION=1.7.13

    - ANDROID_TARGET=10 RUBOTO_PLATFORM=CURRENT

matrix:
  fast_finish: true
  allow_failures:
    # Current master is failing: https://github.com/jruby/jruby/issues/1741
    # Current JRuby 1.7.x gem is failing.  Why?
    - env: ANDROID_TARGET=L RUBOTO_PLATFORM=CURRENT    TEST_PART=1of5
    - env: ANDROID_TARGET=L RUBOTO_PLATFORM=FROM_GEM   TEST_PART=2of5 JRUBY_JARS_VERSION=MASTER
    - env: ANDROID_TARGET=L RUBOTO_PLATFORM=FROM_GEM   TEST_PART=3of5 JRUBY_JARS_VERSION=STABLE
    - env: ANDROID_TARGET=L RUBOTO_PLATFORM=STANDALONE TEST_PART=4of5 JRUBY_JARS_VERSION=MASTER
    - env: ANDROID_TARGET=L RUBOTO_PLATFORM=STANDALONE TEST_PART=5of5 JRUBY_JARS_VERSION=STABLE
    - env: ANDROID_TARGET=L RUBOTO_PLATFORM=STANDALONE TEST_PART=1of5 JRUBY_JARS_VERSION=1.7.15
    - env: ANDROID_TARGET=L RUBOTO_PLATFORM=STANDALONE TEST_PART=2of5 JRUBY_JARS_VERSION=1.7.13
    - env: ANDROID_TARGET=19 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=3of5 JRUBY_JARS_VERSION=MASTER
    - env: ANDROID_TARGET=19 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=4of5 JRUBY_JARS_VERSION=STABLE
    - env: ANDROID_TARGET=19 RUBOTO_PLATFORM=STANDALONE TEST_PART=5of5 JRUBY_JARS_VERSION=MASTER
    - env: ANDROID_TARGET=19 RUBOTO_PLATFORM=STANDALONE TEST_PART=1of5 JRUBY_JARS_VERSION=STABLE
    - env: ANDROID_TARGET=17 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=4of5 JRUBY_JARS_VERSION=MASTER
    - env: ANDROID_TARGET=17 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=5of5 JRUBY_JARS_VERSION=STABLE
    - env: ANDROID_TARGET=17 RUBOTO_PLATFORM=STANDALONE TEST_PART=1of5 JRUBY_JARS_VERSION=MASTER
    - env: ANDROID_TARGET=17 RUBOTO_PLATFORM=STANDALONE TEST_PART=2of5 JRUBY_JARS_VERSION=STABLE
    - env: ANDROID_TARGET=16 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=5of5 JRUBY_JARS_VERSION=MASTER
    - env: ANDROID_TARGET=16 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=1of5 JRUBY_JARS_VERSION=STABLE
    - env: ANDROID_TARGET=16 RUBOTO_PLATFORM=STANDALONE TEST_PART=2of5 JRUBY_JARS_VERSION=MASTER
    - env: ANDROID_TARGET=16 RUBOTO_PLATFORM=STANDALONE TEST_PART=3of5 JRUBY_JARS_VERSION=STABLE
    - env: ANDROID_TARGET=15 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=1of5 JRUBY_JARS_VERSION=MASTER
    - env: ANDROID_TARGET=15 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=2of5 JRUBY_JARS_VERSION=STABLE
    - env: ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=3of5 JRUBY_JARS_VERSION=MASTER
    - env: ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=4of5 JRUBY_JARS_VERSION=STABLE

script:
  - rake install
  - ruboto setup -y -t $ANDROID_TARGET
  - source ~/.rubotorc
  - ruboto emulator -t $ANDROID_TARGET
  - ./run_tests.sh

notifications:
  irc: "irc.freenode.org#ruboto"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fe0d532fe5bef5b7288c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
